version: "2"

networks:
  databases:
    driver: bridge
volumes:
  mongo-data:
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks: 
      - databases

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/mongo-data
    ports:
      - "27017:27017"
    networks: 
      - databases


