version: "2"

networks:
  databases:
    driver: bridge
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks: 
      - databases

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks: 
      - databases


